- name: "Full lifecycle, test, integration"
  hosts: localhost
  become: true

  roles:
    - {role: setup, tags: ["setup"]}
    - {role: test, tags: ["test"]}
    - {role: integration, tags: ["integration"]}
    - {role: cleanup, tags: ["cleanup"]}
