- name: "Full lifecycle, test, integration, deploy"
  hosts: localhost
  become: true

  roles:
    - {role: setup, tags: ["setup"]}
    - {role: test, tags: ["test"]}
    - {role: integration, tags: ["integration"]}
    - {role: deploy, tags: ["deploy"]}
