---
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add Docker APT Repositroy
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Ensure group 'docker' exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to 'docker' group
  ansible.builtin.user:
    name: "admin"
    group: docker
    append: true

- name: Install Node.js
  ansible.builtin.apt:
    name: nodejs
    state: present

- name: Install npm
  ansible.builtin.apt:
    name: npm
    state: present
