---
- name: Build and run MongoDB with docker-compose
  community.docker.docker_compose_v2:
    project_src: "{{ checkout_dir }}"
    state: present
    build: always

- name: Wait for Mongo to accept TCP connections
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: 27017

- name: Wait for app to open port 8080
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: 8080

- name: Call /health endpoint to verify app and DB are working
  ansible.builtin.uri:
    url: http://localhost:8080/health
    method: GET
    status_code: 200
    return_content: true
  register: health_response

- name: Assert MongoDB is connected
  ansible.builtin.assert:
    that:
      - health_response.json.db == "connected"
    fail_msg: "App is running but MongoDB is not connected"
