name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible if not already installed
        run: |
          if ! command -v ansible &> /dev/null; then
            echo "Ansible not found. Installing..."
            sudo apt update
            sudo apt install -y software-properties-common
            sudo add-apt-repository --yes --update ppa:ansible/ansible
            sudo apt install -y ansible
          else
            echo "Ansible is already installed."
          fi
  ansible:
    needs: setup
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Ansible Playbook
        run: ansible-playbook infra/playbook.yml

